# Generated by Django 5.1.7 on 2025-03-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('setting', models.CharField(max_length=255)),
                ('suspect', models.CharField(max_length=255)),
                ('initial_mood', models.IntegerField()),
                ('hostages', models.IntegerField()),
                ('opening_dialogue', models.TextField()),
                ('demand', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=255)),
                ('suspect_type', models.CharField(choices=[('emotional', 'Emotional'), ('pragmatic', 'Pragmatic')], default='pragmatic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='game_scenar_name_e32c6f_idx'), models.Index(fields=['suspect_type'], name='game_scenar_suspect_1e5912_idx')],
            },
        ),
        migrations.AddField(
            model_name='scenarioattempt',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game.scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.scenario'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='scenarioattempt',
            index=models.Index(fields=['scenario'], name='game_scenar_scenari_a12dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['scenario'], name='game_score_scenari_4a246b_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['created_at'], name='game_score_created_32784c_idx'),
        ),
    ]
