# Generated by Django 5.1.7 on 2025-03-25 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_scenario_scenarioattempt_scenario_score_scenario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameprogress',
            options={'verbose_name_plural': 'Game Progress'},
        ),
        migrations.RemoveIndex(
            model_name='gameprogress',
            name='game_gamepr_user_id_b82afa_idx',
        ),
        migrations.RemoveField(
            model_name='gameprogress',
            name='played_date',
        ),
        migrations.RemoveField(
            model_name='gameprogress',
            name='success',
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='completed_scenarios',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='game.scenario'),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='current_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='game.scenario'),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='highest_scenario_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='last_played_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gameprogress',
            index=models.Index(fields=['user', 'last_played_at'], name='game_gamepr_user_id_815e90_idx'),
        ),
    ]
