# Generated by Django 5.1.7 on 2025-03-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'verbose_name': 'Scenario', 'verbose_name_plural': 'Scenarios'},
        ),
        migrations.RemoveIndex(
            model_name='scenario',
            name='game_scenar_name_e32c6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='scenario',
            name='game_scenar_suspect_1e5912_idx',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='suspect_type',
            field=models.CharField(default='pragmatic', max_length=20),
        ),
    ]
