# Generated by Django 5.1.7 on 2025-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_populate_scenarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprogress",
            name="success_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gameprogress",
            name="total_games",
            field=models.IntegerField(default=0),
        ),
    ]
