# Generated by Django 5.1.7 on 2025-03-26 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_gameprogress_success_count_gameprogress_total_games"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="scenarioattempt",
            name="game_scenar_user_id_7c9443_idx",
        ),
        migrations.RemoveIndex(
            model_name="scenarioattempt",
            name="game_scenar_scenari_95e53f_idx",
        ),
        migrations.RemoveIndex(
            model_name="scenarioattempt",
            name="game_scenar_scenari_a12dfb_idx",
        ),
        migrations.RemoveField(
            model_name="scenarioattempt",
            name="guest_identifier",
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="current_hostages",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="current_tension",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="current_trust",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="current_turn",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="emotional_appeals_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="game_over",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="good_choice_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="hostages_released",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="last_input_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="messages",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="poor_choices",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="promises_kept",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="rapport",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="similar_inputs_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scenarioattempt",
            name="final_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="scenarioattempt",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="scenarioattempt",
            name="scenario_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="scenarioattempt",
            name="success",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="scenarioattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
