# Generated by Django 5.1.7 on 2025-03-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_remove_scenarioattempt_game_scenar_user_id_7c9443_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarioattempt",
            name="emotional_labeling_failure",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="emotional_labeling_success",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="emotional_state",
            field=models.CharField(
                choices=[
                    ("volatile", "Volatile (Mood 7+)"),
                    ("agitated", "Agitated (Mood 4-6)"),
                    ("strategic", "Strategic (Mood 2-3)"),
                    ("resigned", "Resigned (Mood 0-1)"),
                ],
                default="agitated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="mirroring_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="tactical_empathy_failure",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioattempt",
            name="tactical_empathy_success",
            field=models.IntegerField(default=0),
        ),
    ]
